name: landgrab
description: A simple AngularDart app
version: 0.0.1
#homepage: https://www.example.com
#author: jwowillo <email@example.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  angular2: ^2.2.0
  cookie: ^0.0.4

dev_dependencies:
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1

transformers:
- angular2:
    platform_directives:
    - 'package:angular2/common.dart#COMMON_DIRECTIVES'
    platform_pipes:
    - 'package:angular2/common.dart#COMMON_PIPES'
    entry_points: web/main.dart
- dart_to_js_script_rewriter
- $dart2js:
    commandLineOptions: [--show-package-warnings]
